<?php

namespace Drupal\sportelli;

use SoapClient;
use SoapVar;
use SoapHeader;
use stdClass;

/**
 *AutoGenerated using wsdl2php 
 */
class getComuneByProvinciaIdRequest {
  public $provinciaId; // integer
}

class getComuneByProvinciaIdResponse {
  public $comune_list; // comune_list
}

class getComuneByComuneIdRequest {
  public $comuneId; // integer
}

class getComuneByComuneIdResponse {
  public $comune; // comune
}

class comune_list {
  public $comune; // comune
}

class comune {
  public $comune_id; // integer
  public $prov_id; // integer
  public $comune_des; // NCName
  public $comune_cod; // NCName
}

class getComuneSistemaByProvinciaIdRequest {
  public $provinciaId; // integer
}

class getComuneSistemaByProvinciaIdResponse {
  public $comune_sistema_list; // comune_sistema_list
}

class comune_sistema_list {
  public $comune_sistema_v; // comune_sistema_v
}

class comune_sistema_v {
  public $comune_id; // integer
  public $prov_id; // integer
  public $comune_des; // NCName
  public $comune_cod; // NCName
  public $sistema_suap2; // boolean
  public $data_attivazione; // dateTime
  public $prov_des; // NCName
  public $prov_cod; // NCName
}

class getProvinciaByRegioneCodRequest {
  public $regioneCod; // string
}

class getProvinciaByRegioneCodResponse {
  public $provincia_list; // provincia_list
}

class provincia_list {
  public $provincia; // provincia
}

class provincia {
  public $prov_id; // integer
  public $prov_des; // NCName
  public $prov_abbr; // NCName
}

class getNazioneRequest {
  public $no_parameter; // string
}

class getNazioneResponse {
  public $nazione_list; // nazione_list
}

class nazione_list {
  public $nazione; // nazione
}

class nazione {
  public $nazione_id; // integer
  public $nazione_abbr; // NCName
  public $nazione_des; // NCName
  public $nazione_cod; // NCName
}


/**
 * metaportService class
 * 
 *  
 * 
 * @author    {author}
 * @copyright {copyright}
 * @package   {package}
 */
class metaportService extends SoapClient {

  private static $classmap = array(
                                    'getComuneByProvinciaIdRequest' => 'getComuneByProvinciaIdRequest',
                                    'getComuneByProvinciaIdResponse' => 'getComuneByProvinciaIdResponse',
                                    'getComuneByComuneIdRequest' => 'getComuneByComuneIdRequest',
                                    'getComuneByComuneIdResponse' => 'getComuneByComuneIdResponse',
                                    'comune_list' => 'comune_list',
                                    'comune' => 'comune',
                                    'getComuneSistemaByProvinciaIdRequest' => 'getComuneSistemaByProvinciaIdRequest',
                                    'getComuneSistemaByProvinciaIdResponse' => 'getComuneSistemaByProvinciaIdResponse',
                                    'comune_sistema_list' => 'comune_sistema_list',
                                    'comune_sistema_v' => 'comune_sistema_v',
                                    'getProvinciaByRegioneCodRequest' => 'getProvinciaByRegioneCodRequest',
                                    'getProvinciaByRegioneCodResponse' => 'getProvinciaByRegioneCodResponse',
                                    'provincia_list' => 'provincia_list',
                                    'provincia' => 'provincia',
                                    'getNazioneRequest' => 'getNazioneRequest',
                                    'getNazioneResponse' => 'getNazioneResponse',
                                    'nazione_list' => 'nazione_list',
                                    'nazione' => 'nazione',
                                   );

  public function metaportService($wsdl = "http://172.30.253.137:8090/suap2/ws/meta/metaws.wsdl", $options = array()) {
    foreach(self::$classmap as $key => $value) {
      if(!isset($options['classmap'][$key])) {
        $options['classmap'][$key] = $value;
      }
    }
    parent::__construct($wsdl, $options);
  }

  /**
   *  
   *
   * @param getComuneByComuneIdRequest $getComuneByComuneIdRequest
   * @return getComuneByComuneIdResponse
   */
  public function getComuneByComuneId(getComuneByComuneIdRequest $getComuneByComuneIdRequest) {
    return $this->__soapCall('getComuneByComuneId', array($getComuneByComuneIdRequest),       array(
            'uri' => 'http://www.sardegnasuap.it/schema',
            'soapaction' => ''
           )
      );
  }

  /**
   *  
   *
   * @param getNazioneRequest $getNazioneRequest
   * @return getNazioneResponse
   */
  public function getNazione(getNazioneRequest $getNazioneRequest) {
    return $this->__soapCall('getNazione', array($getNazioneRequest),       array(
            'uri' => 'http://www.sardegnasuap.it/schema',
            'soapaction' => ''
           )
      );
  }

  /**
   *  
   *
   * @param getComuneSistemaByProvinciaIdRequest $getComuneSistemaByProvinciaIdRequest
   * @return getComuneSistemaByProvinciaIdResponse
   */
  public function getComuneSistemaByProvinciaId(getComuneSistemaByProvinciaIdRequest $getComuneSistemaByProvinciaIdRequest) {
    return $this->__soapCall('getComuneSistemaByProvinciaId', array($getComuneSistemaByProvinciaIdRequest),       array(
            'uri' => 'http://www.sardegnasuap.it/schema',
            'soapaction' => ''
           )
      );
  }

  /**
   *  
   *
   * @param getProvinciaByRegioneCodRequest $getProvinciaByRegioneCodRequest
   * @return getProvinciaByRegioneCodResponse
   */
  public function getProvinciaByRegioneCod(getProvinciaByRegioneCodRequest $getProvinciaByRegioneCodRequest) {
    return $this->__soapCall('getProvinciaByRegioneCod', array($getProvinciaByRegioneCodRequest),       array(
            'uri' => 'http://www.sardegnasuap.it/schema',
            'soapaction' => ''
           )
      );
  }

  /**
   *  
   *
   * @param getComuneByProvinciaIdRequest $getComuneByProvinciaIdRequest
   * @return getComuneByProvinciaIdResponse
   */
  public function getComuneByProvinciaId(getComuneByProvinciaIdRequest $getComuneByProvinciaIdRequest) {
    return $this->__soapCall('getComuneByProvinciaId', array($getComuneByProvinciaIdRequest),       array(
            'uri' => 'http://www.sardegnasuap.it/schema',
            'soapaction' => ''
           )
      );
  }

}

?>
