module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adv_varnish: 0
  automated_cron: 0
  back_to_top: 0
  bandi: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_translation: 0
  content_moderation: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_reference_revisions: 0
  entityqueue: 0
  eu_cookie_compliance: 0
  facets: 0
  facets_summary: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  help: 0
  image: 0
  lang_dropdown: 0
  language: 0
  libraries: 0
  link: 0
  linkit: 0
  locale: 0
  mailchimp: 0
  mailchimp_campaign: 0
  mailchimp_lists: 0
  mailchimp_signup: 0
  menu_block: 0
  menu_ui: 0
  metatag: 0
  metatag_views: 0
  node: 0
  options: 0
  override_node_options: 0
  page_cache: 0
  path: 0
  rabbit_hole: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  rest: 0
  rest_menu_items: 0
  restui: 0
  rh_node: 0
  rh_taxonomy: 0
  role_delegation: 0
  search_api: 0
  search_api_glossary: 0
  search_api_pantheon: 0
  search_api_solr: 0
  search_api_views_taxonomy: 0
  serialization: 0
  shortcut: 0
  si8_utils: 0
  simple_sitemap: 0
  sitemap: 0
  slick: 0
  slick_entityreference: 0
  slick_ui: 0
  smart_trim: 0
  smtp: 0
  sportelli: 0
  system: 0
  taxonomy: 0
  text: 0
  theme_change: 0
  token: 0
  toolbar: 0
  toolbar_menu: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_accordion: 0
  views_data_export: 0
  views_ui: 0
  viewsreference: 0
  workflows: 0
  youtube: 0
  menu_admin_per_menu: 1
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  si8: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: it
