fields:
  block_content:
    langcode:
      type: hidden
      settings: {  }
    info:
      type: hidden
      settings: {  }
    changed:
      type: hidden
      settings: {  }
    revision_created:
      type: hidden
      settings: {  }
    revision_user:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    body:
      type: text_summary_field_diff_builder
      settings:
        compare_format: 0
        compare_summary: 0
        show_header: 1
        markdown: drupal_html_to_text
  content_moderation_state:
    langcode:
      type: hidden
      settings: {  }
    uid:
      type: hidden
      settings: {  }
    workflow:
      type: hidden
      settings: {  }
    moderation_state:
      type: hidden
      settings: {  }
    content_entity_type_id:
      type: hidden
      settings: {  }
    content_entity_id:
      type: hidden
      settings: {  }
    content_entity_revision_id:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
  node:
    langcode:
      type: hidden
      settings: {  }
    status:
      type: hidden
      settings: {  }
    title:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    uid:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    created:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    changed:
      type: hidden
      settings: {  }
    promote:
      type: hidden
      settings: {  }
    sticky:
      type: hidden
      settings: {  }
    revision_timestamp:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    content_translation_source:
      type: hidden
      settings: {  }
    content_translation_outdated:
      type: hidden
      settings: {  }
    body:
      type: text_field_diff_builder
      settings:
        compare_format: 0
        show_header: 1
        markdown: drupal_html_to_text
