youtube_suggest: false
youtube_modestbranding: true
youtube_theme: true
youtube_color: false
youtube_enablejsapi: false
youtube_wmode: true
youtube_privacy: false
youtube_player_class: youtube-field-player
youtube_thumb_dir: youtube
youtube_thumb_hires: true
youtube_thumb_token_image_style: ''
_core:
  default_config_hash: VwsEKAIzxzP5iOJe4jeFBgV701WR47ir2hOu-Ug1QRg
langcode: it
