display:
  default:
    display_options:
      title: 'Ayuda a las empresas'
      header:
        result:
          content: 'Usted tiene <strong>@total</strong> apoyos para las empresas'
  bandi:
    display_options:
      display_extenders:
        metatag_display_extender:
          metatags:
            title: 'Ayuda a las empresas | SardegnaImpresa'
  archivio:
    display_options:
      display_extenders:
        metatag_display_extender:
          metatags:
            title: 'Ayuda a las empresas, archivo | SardegnaImpresa'
      title: 'Ayuda a las empresas, archivo'
